### ISSUE TITLE
Schroeven

### ISSUE THREAD

**Issue by m-m-m-m-m-m-m-m-m-m-m-m** [sebastius/klikenklaaraandemuur#1]
Hi @sebastius,

Ik vroeg me af welke schroeven je hebt gebruikt om de beugel te klemmen?

**Comment by sebastius** [comment]
Ik vermoed iets metrisch. M3 of M4, weet het niet meer. Moet je gewoon even proberen :)

**Comment by sebastius** [comment]
Klopt, geen moertje in het frame, direct inschroeven. Werkt redelijk :)

Bas

**Comment by m-m-m-m-m-m-m-m-m-m-m-m** [comment]
Helder, bedankt voor je snelle reactie!
